export default () => ({
  cdnImgUrl: 'https://canvas-cdn.s3.eu-west-2.amazonaws.com/img/istasyonyurtlari/',
  // pariette: 'https://pardev.pariette.com/api/',
  pariette: 'http://127.0.0.1:8000/api/',
  token: '113VP3nHVC34ZrizRsF7TDmQlwJ3DwitIqLwzWhKr7m3NE8wVxGMsdC8CizAmKIq',
  authUser: null,
  locales: ['tr'],
  locale: 'tr',
  start: 0,
  end: 10,
  settings: {
    title: 'istasyon yurtları',
    url: 'https://www.istasyonyurtlari.com.tr/',
    desc: '05415966667 Esenyurt ve Merter, Çevre üniversitelere ücretsiz servis imkanı',
    keywords: '',
    lang: 'tr_TR',
    copyright: '© Tüm Hakları Saklıdır',
    favicon: 'favicon.png',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
    linkedin: 'https://www.linkedin.com/',
    twitter: 'https://twitter.com/',
    youtube: 'https://www.youtube.com/',
    email: 'info@istasyonyurtlari.com.tr',
    tel1: '+902124501063',
    tel1Title: '+90 212 450 10 63',
    tel2: '+905415966667',
    tel2Title: '+90 541 596 66 67'
  },
  // new
  layout: [],
  keyData: [],
  // new
  navigation: [],
  navigationFooter: [],
  bannerkey: [],
  bannerurl: [],
  bannerhomepage: [],
  bannerallpages: [],
  bannerallcats: [],
  bannerallblogs: [],
  bannerallnews: [],
  blogs: [],
  page: [],
  modalShow: false,
  popupShow: true
})
