export default () => ({
  // cdnImgUrl: 'https://canvas-cdn.s3.eu-west-2.amazonaws.com/img/istasyonyurtlari/',
  cdnImgUrl: 'http://127.0.0.1:8000/storage/',
  // pariette: 'https://pardev.pariette.com/api/',
  pariette: 'http://127.0.0.1:8000/api/',
  token: '113VP3nHVC34ZrizRsF7TDmQlwJ3DwitIqLwzWhKr7m3NE8wVxGMsdC8CizAmKIq',
  authUser: null,
  showAdmin: false,
  locales: ['tr'],
  locale: 'tr',
  start: 0,
  end: 10,
  settings: {
    title: 'istasyon yurtları',
    url: 'https://www.istasyonyurtlari.com.tr/',
    desc: '05415966667 Esenyurt ve Merter, Çevre üniversitelere ücretsiz servis imkanı',
    keywords: '',
    lang: 'tr_TR',
    copyright: '© Tüm Hakları Saklıdır',
    favicon: 'favicon.png',
    instagram: 'https://www.instagram.com/',
    facebook: 'https://www.facebook.com/',
    linkedin: 'https://www.linkedin.com/',
    twitter: 'https://twitter.com/',
    youtube: 'https://www.youtube.com/',
    email: 'info@istasyonyurtlari.com.tr',
    tel1: '+902124501063',
    tel1Title: '+90 212 450 10 63',
    tel2: '+905415966667',
    tel2Title: '+90 541 596 66 67'
  },
  tynmceOpt: {
    directionality: 'ltr',
    language: 'tr',
    plugins: [
      'image imagetools',
      'advlist autolink lists link image charmap print preview anchor',
      'searchreplace visualblocks code fullscreen',
      'insertdatetime media table paste imagetools wordcount searchreplace',
      'autolink autoresize emoticons code media table'
    ],
    toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify',
    toolbar2: 'searchreplace paste pastetex | link image media | emoticons code | bullist numlist outdent indent | table tabledelete',
    content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
  },
  // new
  layout: [],
  keyData: [],
  // new
  isSaved: true,
  navigation: [],
  navigationFooter: [],
  galleryRows: [],
  bannerkey: [],
  bannerurl: [],
  bannerhomepage: [],
  bannerallpages: [],
  bannerallcats: [],
  bannerallblogs: [],
  bannerallnews: [],
  blogs: [],
  page: [],
  modalShow: false,
  popupShow: true
})
